service: arc-publisher
useDotenv: true

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_DEFAULT_REGION}
  environment:
    # AWS_REGION: ${env:AWS_DEFAULT_REGION}
    EC_STORY_API: ${env:EC_STORY_API_${self:provider.stage}}
    EC_API_TOKEN: ${env:EC_API_TOKEN_${self:provider.stage}}
    STORY_AUTHOR_ID: ${env:STORY_AUTHOR_ID_${self:provider.stage}}
    STORY_OWNER: ${env:STORY_OWNER_${self:provider.stage}}

functions:
  app:
    handler: wsgi_handler.handler
    timeout: 60
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

  # cronPublisher:
  #   handler: app.run
  #   events:
  #     - schedule: cron(00 06 * * ? *)